pylint

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,36 +1,44 @@
-name: Python application
+name: Run Unit Tests and Linting, and Block Pull Request
 
 on:
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
-
-permissions:
-  contents: read
+    branches:
+      - main  
+  workflow_dispatch:  # Add workflow_dispatch to allow manual triggering
 
 jobs:
-  build:
-
+  test-and-pr:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.12.2"
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
-      run: |
-        pytest
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'  
+
+      - name: Install Pylint
+        run: |
+          python -m pip install --upgrade pip
+          pip install pylint
+
+      - name: Run Unit Tests
+        run: python3 unit_tests.py
+        continue-on-error: true  # Continue even if tests fail, we'll check the status later
+
+      - name: Run Linter
+        run: pylint toDoList.py
+        continue-on-error: true  # Continue even if linting fails, we'll check the status later
+
+      # - name: Check Test and Lint Results
+      #   run: exit $(($? + $?))
+        # This will exit with a non-zero status if any of the previous steps failed
+
+      # - name: Create Pull Request
+      #   if: always()
+      #   uses: peter-evans/create-pull-request@v6.0.2
+      #   with:
+      #     title: Unit Tests and Linting
+      #     base: main
